### PR TITLE
Liyu

### PR DESCRIPTION
**Pull request by liyuxiao2**
Intialized, the medium problem, set up test cases but havent started yet. Improved the "easy solution, incorporating both while loops into 1.

### CODE REVIEW

**Comment by liyuxiao2** [comment]
finished remove linked list elems(2), under medium problems. Used a dictionary to keep track of the key,value pairs that needed to be removed. Kept same logic as before from remove linked list elems(1) when removing elems.

**Comment by saixiao** [comment]
nit: folder named removelinkedlist(2), should just be removelinkedlist

**Comment by saixiao** [comment]
In general you don't need to commit your binary files. I assume this is what your compiler generates so you can run locally. You can add a git ignore rule to filter out files like this.

**Comment by saixiao** [comment]
ditto for pip file. This repo is just to keep code solutions.

**Pull request merged**
